In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
ds = pd.read_csv(r"C:\Users\sujan\Downloads\dataset_website.csv")

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
x_train


array([[ 1, -1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  0,  1],
       [-1, -1,  1, ...,  1,  1, -1],
       ...,
       [-1,  1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  1,  1]], dtype=int64)

In [10]:
x_test

array([[ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  1,  1],
       ...,
       [-1, -1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  1,  1]], dtype=int64)

In [11]:
y_train


array([ 1, -1, -1, ...,  1, -1, -1], dtype=int64)

In [12]:
y_test

array([-1, -1, -1, ...,  1,  1,  1], dtype=int64)

In [13]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [14]:
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9167797376752601

In [17]:
import pickle
pickle.dump(lr,open('Phishing_Website.pkl','wb'))